### PR TITLE
Channel naming changes / minor changes

### PR DESCRIPTION
**Pull request by eren-kemer**
Corrected the channel naming of Failure counts, to make it more clear what it stands for.
Fails and Failed are very easy to confuse.
Also changed SessionResport to SessionsReport

Didn't test yet.

### CODE REVIEW

**Comment by mycloudrevolution** [comment]
Thanks for contributing!
Although I like the changes I am not sure that changes to the channel names are a good idea. Existing Installations will break after updating... And you can not remove a channel in PRTG...

**Comment by eren-kemer** [comment]
I've also had to remove prtg sensors and readd them in the past
It also happens on deleting, disabling, removing, renaming jobs etc., so I guess people should be used to readding sensors. At least, that's my experience so far. 
I really hope prtg takes care of that feature request at some point...

**Comment by eren-kemer** [comment]
Could we get this as a second branch perhaps, at least for now?

**Comment by mycloudrevolution** [comment]
Hello,

as long as the channel naming is changed I will not merge this Pull Request.

If you need the actual state, just create a fork into a new repositoryor create a clone.

**Pull request closed without merging**
