### PR TITLE
Ps remoting

### PR DESCRIPTION
**Pull request by FrelVick**
https://github.com/mycloudrevolution/Advanced-PRTG-Sensors/issues/1
PSRemoting added
Smooth error handling

### CODE REVIEW

**Comment by mycloudrevolution** [comment]
Hello @FrelVick ,
Thanks for your great work and for contributing to this script!

But we need to ensure that all existing installations can upgrade to the new version. So, might you please think about these changes:

1. Default behavior needs to be local PSSnapin
2. Optional parameter for PS-Remoting

Best regards,
Markus

**Comment by FrelVick** [comment]
I've added the PSRemoting switch. 
I suggest to warn the user using PRTG message channel and pass to the PSRemoting by default, since you don't need to deploy the Veam snapin on our PRTG's probes, neither use a 64bits PowerShell environment

**Comment by mycloudrevolution** [comment]
With the PSRemoting switch, your enhancements are fine for me. I really like the "Trap" idea!
I have tested with Veeam 9.5 U3a on a Windows 2012 R2 with PS 5.1.

Issue Resolved within this Pull Request: #1 

In my environment, a new issue came up with this Version **(Not PSRemote)**: #37 

Might you please verify that in your environment?

**Comment by mycloudrevolution** [comment]
I have added a Commit to this PR to resolve the issue #37 

Might you please verify that in your environment?

**Comment by FrelVick** [comment]
Work for me.
We could push it

**Pull request merged**
